version: '3.1'

services:

  prosody-storage:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    container_name: prosody-storage
    ports:
      - 3306:3306
